#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-jopt-simple
Version  : 5.0.2
Release  : 1
URL      : https://github.com/jopt-simple/jopt-simple/archive/jopt-simple-5.0.2.tar.gz
Source0  : https://github.com/jopt-simple/jopt-simple/archive/jopt-simple-5.0.2.tar.gz
Source1  : https://repo1.maven.org/maven2/net/sf/jopt-simple/jopt-simple/3.2/jopt-simple-3.2.jar
Source2  : https://repo1.maven.org/maven2/net/sf/jopt-simple/jopt-simple/3.2/jopt-simple-3.2.pom
Source3  : https://repo1.maven.org/maven2/net/sf/jopt-simple/jopt-simple/5.0.2/jopt-simple-5.0.2.jar
Source4  : https://repo1.maven.org/maven2/net/sf/jopt-simple/jopt-simple/5.0.2/jopt-simple-5.0.2.pom
Source5  : https://repo1.maven.org/maven2/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
Source6  : https://repo1.maven.org/maven2/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: mvn-jopt-simple-data = %{version}-%{release}

%description
[![Build Status](https://travis-ci.org/pholser/jopt-simple.svg?branch=master)](https://travis-ci.org/pholser/jopt-simple)

%package data
Summary: data components for the mvn-jopt-simple package.
Group: Data

%description data
data components for the mvn-jopt-simple package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/sf/jopt-simple/jopt-simple/3.2
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/net/sf/jopt-simple/jopt-simple/3.2/jopt-simple-3.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/sf/jopt-simple/jopt-simple/3.2
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/net/sf/jopt-simple/jopt-simple/3.2/jopt-simple-3.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/sf/jopt-simple/jopt-simple/5.0.2
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/net/sf/jopt-simple/jopt-simple/5.0.2/jopt-simple-5.0.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/sf/jopt-simple/jopt-simple/5.0.2
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/net/sf/jopt-simple/jopt-simple/5.0.2/jopt-simple-5.0.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/sf/jopt-simple/jopt-simple/5.0.4
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/net/sf/jopt-simple/jopt-simple/5.0.4
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/net/sf/jopt-simple/jopt-simple/3.2/jopt-simple-3.2.jar
/usr/share/java/.m2/repository/net/sf/jopt-simple/jopt-simple/3.2/jopt-simple-3.2.pom
/usr/share/java/.m2/repository/net/sf/jopt-simple/jopt-simple/5.0.2/jopt-simple-5.0.2.jar
/usr/share/java/.m2/repository/net/sf/jopt-simple/jopt-simple/5.0.2/jopt-simple-5.0.2.pom
/usr/share/java/.m2/repository/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
/usr/share/java/.m2/repository/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.pom
